version: '2.1'
services:
  terminalserver:
    build: ./
    image: wisfern/uxrdp
    container_name: uxrdp
    hostname: terminalserver
    restart: always
    shm_size: 1g
    environment:
       PASSWORDHASH: $$1$$z53Cg/fV$$06o379IvIOxj/ESruVKrG1
       IDLETIME: 11
    ports:
      - "3389:3389"
      - "2222:22"
    volumes:
      - ssh:/etc/ssh/
      - /home/:/home/

volumes:
  ssh:
